name: namer_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:  # Única sección de dependencias
  flutter:
    sdk: flutter
  provider: ^6.0.0  # Dependencia de Provider
  flutter_animate: ^4.1.1+1  # Dependencia para animaciones

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true